[workspace]
members = ["packages/sotto_vesu_anonymizer"]

[workspace.package]
version = "0.1.0"
edition = "2024_07"

[workspace.dependencies]
starknet = "2.17.0"
openzeppelin = "3.0.0"
privacy = { git = "https://github.com/starkware-libs/starknet-privacy", rev = "66e3caae8c0201227a6719696d004e30d90aea65" }

[workspace.tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
sierra = true
casm = true
